language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: f66hhf3sMnR2SeOsuibEjlTm+F82f2GWYJmO4SmAYT7pXvfz1dY0EQz3c16fd1MuyJGUDIbmFAMJGFPUI96MU05mCkMUPOSv1yovrijzzlKXFY6pnHapPEHA1AmVfIGZOuHTlXi1KeSp05QVkgj8HxiKNOv++ciIQKPbvG3YmDWj2BtkIQDEmbXeoFrDbc90e5f4MlmYGdg3ODgGykWc17k9pPAp48qbr7b4IvPmPn2SOPMVh2kXfklVQnkvxryJgLGBmflvNU0pupM+rxR0Hykc8Jbr27mIyug4TkKC/6Dvm12dU0MKbBH+ZGvfw5heBvbhusrvjktPrbBaz0ELiGEIU/CsAgSUbupAHwaG8xYYzSadRcZW+2s57jrGkruvZCWwjYXYXY0HKVbRbH/cYuI7wggvojdoz8rjHQdKnxtLx7hmS1xi3vhsjPq8CuaO+xboL4xzCbX1wTvVE2UVp9PQZbsII+3zAO+gUZZx/FqizhCSRuB5zQVoIIijhG/oGxLh9eBGLmiTqrI5KR7UVEE8jK+XW4O9Khcp0nq/pguM/YmD71KhqVI3H1y8LcmGtySrYXdctxb8Oljt6jZs0T6I3jRSOTKlU1+cb7ql93+dZ6e4s5kUEupc6YNKPp/l60yVOvcu0wfdJP7WA2nGcYMliiXNBzha14FapzUUiVQ=
  app: information-retrieval
